[17/Jun/2017 02:46:23] INFO [django.server:124] "GET / HTTP/1.1" 200 2163
[17/Jun/2017 02:46:34] INFO [django.server:124] "GET /get_item/Ankyros%20Prime%20Blueprint HTTP/1.1" 301 0
[17/Jun/2017 02:46:35] ERROR [django.request:135] Internal Server Error: /get_item/Ankyros Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: item.html
[17/Jun/2017 02:46:35] ERROR [django.server:124] "GET /get_item/Ankyros%20Prime%20Blueprint/ HTTP/1.1" 500 27
[17/Jun/2017 02:46:35] WARNING [django.request:152] Not Found: /favicon.ico
[17/Jun/2017 02:46:35] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 85
[17/Jun/2017 02:47:29] ERROR [django.request:135] Internal Server Error: /get_item/Ankyros Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: item.html
[17/Jun/2017 02:47:29] ERROR [django.server:124] "GET /get_item/Ankyros%20Prime%20Blueprint/ HTTP/1.1" 500 27
[17/Jun/2017 02:47:33] INFO [django.server:124] "GET / HTTP/1.1" 200 2163
[17/Jun/2017 02:47:37] INFO [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint HTTP/1.1" 301 0
[17/Jun/2017 02:47:38] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: item.html
[17/Jun/2017 02:47:38] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 27
[17/Jun/2017 02:50:34] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/cached.py", line 60, in get_template
    template_name, template_dirs, skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unknown argument for u'include' tag: u"'components/scripts.html'".
[17/Jun/2017 02:50:34] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 27
[17/Jun/2017 02:50:37] INFO [django.server:124] "GET / HTTP/1.1" 200 2163
[17/Jun/2017 02:50:41] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Link/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/cached.py", line 60, in get_template
    template_name, template_dirs, skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unknown argument for u'include' tag: u"'components/scripts.html'".
[17/Jun/2017 02:50:41] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Link/ HTTP/1.1" 500 27
[17/Jun/2017 02:52:08] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Link/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/cached.py", line 60, in get_template
    template_name, template_dirs, skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unknown argument for u'include' tag: u"'components/scripts.html'".
[17/Jun/2017 02:52:08] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Link/ HTTP/1.1" 500 27
[17/Jun/2017 02:52:16] DEBUG [django.db.backends:91] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[17/Jun/2017 02:52:16] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[17/Jun/2017 02:52:19] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Link/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unknown argument for u'include' tag: u"'components/scripts.html'".
[17/Jun/2017 02:52:19] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Link/ HTTP/1.1" 500 151844
[17/Jun/2017 03:12:39] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Link/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unknown argument for u'include' tag: u"'components/scripts.html'".
[17/Jun/2017 03:12:39] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Link/ HTTP/1.1" 500 153413
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /get_item/Akbronco%20Prime%20Link/ HTTP/1.1" 200 19585
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/css/get_item.css HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/css/stretchy.css HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/css/typeaheadjs.css HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/js/jquery.min.js HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/js/typeahead.js HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/js/search.js HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/img/duc.png HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/img/plat.png HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/img/bg.jpg HTTP/1.1" 304 0
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:13:02] INFO [django.server:124] "GET /static/img/favicon-32x32.png HTTP/1.1" 304 0
[17/Jun/2017 03:13:12] INFO [django.server:124] "GET / HTTP/1.1" 200 2007
[17/Jun/2017 03:13:12] INFO [django.server:124] "GET /static/css/home.css HTTP/1.1" 304 0
[17/Jun/2017 03:17:15] INFO [django.server:124] "GET / HTTP/1.1" 200 2007
[17/Jun/2017 03:17:15] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:17:18] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 21: 'static', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[17/Jun/2017 03:17:19] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 149960
[17/Jun/2017 03:17:45] INFO [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 200 8042
[17/Jun/2017 03:17:46] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:18:56] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: scripts.html
[17/Jun/2017 03:18:57] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 175023
[17/Jun/2017 03:19:17] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 516, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 534, in extend_nodelist
    token, '%r must be the first tag in the template.' % node,
TemplateSyntaxError: <ExtendsNode: extends "scripts.html"> must be the first tag in the template.
[17/Jun/2017 03:19:18] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 171409
[17/Jun/2017 03:20:37] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: scripts.html
[17/Jun/2017 03:20:37] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 173819
[17/Jun/2017 03:20:50] ERROR [django.request:135] Internal Server Error: /get_item/Akbronco Prime Blueprint/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwcorle/Documents/better_getter/get_item/views.py", line 161, in get_item_details
    return render(request, 'item.html', context)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 1: 'static'. Did you forget to register or load this tag?
[17/Jun/2017 03:20:50] ERROR [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 500 186464
[17/Jun/2017 03:21:18] INFO [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 200 8339
[17/Jun/2017 03:21:18] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:23:22] INFO [django.server:124] "GET /get_item/Akbronco%20Prime%20Blueprint/ HTTP/1.1" 200 8398
[17/Jun/2017 03:23:22] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:30:48] INFO [django.server:124] "GET / HTTP/1.1" 200 406
[17/Jun/2017 03:31:20] INFO [django.server:124] "GET / HTTP/1.1" 200 1984
[17/Jun/2017 03:31:21] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:31:23] INFO [django.server:124] "GET / HTTP/1.1" 200 1984
[17/Jun/2017 03:31:23] INFO [django.server:124] "GET /static/img/favicon-16x16.png HTTP/1.1" 200 742
[17/Jun/2017 03:31:26] INFO [django.server:124] "GET /get_item/Ankyros%20Prime%20Blade/ HTTP/1.1" 200 14001
[17/Jun/2017 03:31:39] INFO [django.server:124] "GET /get_item/Ankyros%20Prime%20Blade/ HTTP/1.1" 200 14001
[17/Jun/2017 03:31:44] INFO [django.server:124] "GET /get_item/Point%20Blank HTTP/1.1" 301 0
[17/Jun/2017 03:31:45] INFO [django.server:124] "GET /get_item/Point%20Blank/ HTTP/1.1" 200 9207
